threshold: 0.5
possible_classes:
  organics: [Banana, Carrot, Apple]
  condiments: [Mayonnaise, Ketchup]
  hygiene_products: [Soap, Napkin, Toothpaste, Alcohol Bottle]
  derivatives: [Yeast, Chocolate Powder, Coconut Milk]
  drinks: [Grape Juice, Chocolate Milk, Soda can, Beer can]
  groceries: [Popcorn, Chocolate, Gelatine, Cracker]
  people: [person]